#!/bin/bash

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


#
# chkconfig: 35 90 12
# description: NCPA Listener
#
# Start the service

BASEDIR=/usr/local/ncpa

start() {
        (
            cd $BASEDIR
            $BASEDIR/ncpa_posix_listener --start
        )
        echo "Started listener..."
}
# Restart the service
stop() {
        (
            cd $BASEDIR
            /usr/local/ncpa/ncpa_posix_listener --stop
            echo "Exited."
        )   
}
# Get the status
status() {
        if [ -f /usr/local/ncpa/var/ncpa_posix_listener.pid];
        then
            pid=`cat /usr/local/ncpa/var/ncpa_posix_listener.pid`
            echo "Process running with PID $pid"
        else
            echo "Process is not running."
        fi
}


### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
