#!/bin/bash

### BEGIN INIT INFO
# Provides:          ncpa_passive 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Enables the NCPA listener.
### END INIT INFO

BASEDIR=/usr/local/ncpa
start() {
        (
            cd $BASEDIR
            $BASEDIR/ncpa_posix_passive --start
        )
        echo "Started passive agent..."
}
# Restart the service
stop() {
        (
            cd $BASEDIR
            $BASEDIR/ncpa_posix_passive --stop
        )
        echo "Exited."
}
# Get the status
status() {
        if [ -f /usr/local/ncpa/var/ncpa_posix_passive.pid ];
        then
            pid=`cat /usr/local/ncpa/var/ncpa_posix_passive.pid`
            echo "Process running with PID $pid"
        else
            echo "Process is not running."
        fi
}


### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
