#!/bin/bash

### BEGIN INIT INFO
# Provides:          ncpa_passive 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This manages the NCPA Passive service
# Description:       NCPA is a cross platform monitoring agent for Nagios that requires no dependencies.
### END INIT INFO

# init.d / servicectl compatibility (openSUSE)
if [ -f /etc/rc.status ]; then
    . /etc/rc.status
    rc_reset
fi

# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

_BASEDIR_

# Start NCPA Passive service
start() {
    action "Starting NCPA Passive: " $BASEDIR/ncpa_posix_passive --start
}

# Stop NCPA Passive service
stop() {
    action "Stopping NCPA Passive: " $BASEDIR/ncpa_posix_passive --stop
}

# Get the status of the NCPA Passive service
ncpa_p_status() {
    output=`$BASEDIR/ncpa_posix_passive --status`
    echo "NCPA Passive $output"
}

# Main init script logic
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        ncpa_p_status
        ;;
    restart|reload|condrestart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
