name: Multi-OS Python Matrix

on:
  push:
    branches: [ 'cpd-test-actions-build-windows' ]

jobs:
  # 1. Primary job that your deployment depends on
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: python -VV

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: python -VV

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: python -VV

  e2e-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - run: echo "Ubuntu tests finished!"

  e2e-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - run: Write-Host "Windows tests finished!"

  e2e-macos:
    runs-on: macos-latest
    needs: build-macos
    steps:
      - run: echo "macOS tests finished!"
