name: Build Linux

on:
  push:
    branches: [ 'cpd-test-actions-build-windows' ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: '3.13'

      - name: Build project
        working-directory: build
        run: |
          sudo ./build.sh

      - name: Run unit tests
        run: |
          source build/venvs/ncpa-build-linux/bin/activate
          sudo python -m pip install pytest
          sudo pytest -v
          deactivate

      - name: Test Linux Install
        run: |
          sudo apt install -y ./ncpa*.deb

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Ensure service is running
        run: |
          sudo systemctl is-active ncpa

      - name: Test API
        run: |
          curl -k 'https://127.0.0.1:5693/api/system/agent_version?token=mytoken'

      - name: Upload RPM installer
        uses: actions/upload-artifact@v7
        with:
          name: ncpa-rpm
          path: build/*.rpm
          overwrite: true

      - name: Upload DEB installer
        uses: actions/upload-artifact@v7
        with:
          name: ncpa-deb
          path: build/*.deb
          overwrite: true
