name: macOS e2e Test

on:
  push:
    branches: [ 'cpd-test-actions-build-windows' ]

jobs:
  build-macos:
    runs-on: macos-15-intel
    
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: '3.13'

      - name: Build project
        working-directory: build
        run: sudo ./build.sh

      # The GH macOS runner default hostnames are too long and cause issues generating SSL certificates
      # Specifically this causes issues with the unit tests related to SSL certificate generation
      - name: Change macOS Hostname
        run: |
          NEW_HOSTNAME="gh-macos-runner"
          
          sudo scutil --set HostName "${NEW_HOSTNAME}.local"
          sudo scutil --set LocalHostName "${NEW_HOSTNAME}"
          sudo scutil --set ComputerName "${NEW_HOSTNAME}"
          
          # Optional: Flush DNS cache to apply changes immediately
          dscacheutil -flushcache

      - name: Run Unit Tests
        run: |
          sudo chown -R $USER build/
          source build/venvs/ncpa-build-darwin/bin/activate
          python -m pip install pytest
          pytest -v
          deactivate

      - name: Upload macOS Installer
        uses: actions/upload-artifact@v7
        with:
          name: ncpa-macOS
          path: build/*.dmg
          overwrite: true

  e2e-macos:
    runs-on: macos-15-intel
    needs: build-macos # Crucial: Enforces sequential execution
    steps:
      - uses: actions/checkout@v7

      - name: Download Build Artifact
        uses: actions/download-artifact@v7
        with:
          name: ncpa-macOS
          path: downloaded-assets/

      - name: Verify Artifact File
        run: ls -l ./downloaded-assets/ncpa*.dmg

      # The GH macOS runner default hostnames are too long and cause issues generating SSL certificates
      # Specifically this causes issues with the unit tests related to SSL certificate generation
      - name: Change macOS Hostname
        run: |
          NEW_HOSTNAME="gh-macos-runner"
          
          sudo scutil --set HostName "${NEW_HOSTNAME}.local"
          sudo scutil --set LocalHostName "${NEW_HOSTNAME}"
          sudo scutil --set ComputerName "${NEW_HOSTNAME}"
          
          # Optional: Flush DNS cache to apply changes immediately
          dscacheutil -flushcache

      - name: Test macOS Install
        run: |
          sudo hdiutil attach -nobrowse ./downloaded-assets/ncpa*.dmg
          sudo zsh /Volumes/NCPA*/install.sh

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Ensure Service is Running
        run: sudo launchctl list | grep ncpa

      - name: Test API Sanity Check
        run: curl -k 'https://127.0.0.1:5693/api/system/agent_version?token=mytoken'

      - name: Copy Custom Plugin
        run: sudo cp ./test/e2e/plugins/check_os.sh /usr/local/ncpa/plugins/

      - name: Run E2E Tests
        run: bash ./test/e2e/test_ncpa_e2e.sh 
