name: Windows e2e Test

on:
  workflow_run:
    workflows: ["Build Windows"]
    types:
      - completed

jobs:
  deploy-windows:
    runs-on: windows-2022
   # Only execute if the upstream build workflow actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v7

      - name: Download Cross-Workflow Artifact
        uses: actions/download-artifact@v7
        with:
          name: ncpa-windows
          # Crucial inputs needed when downloading from a different workflow:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Windows Install
        working-directory: build
        run: |
          Start-Process -FilePath ".\ncpa*.exe" -ArgumentList "/S", "/TOKEN='8675309'" -Wait

      - name: Sleep for 10 seconds
        run: Start-Sleep -s 10
        shell: powershell

      - name: Ensure service is running
        run: |
          Get-Service NCPA

      - name: Test API Sanity Check
        run: |
          curl.exe -k 'https://127.0.0.1:5693/api/system/agent_version?token=8675309'

      - name: Copy Custom Plugin
        run: |
          Copy-Item -Path "test\e2e\plugins\check_os.ps1" -Destination "C:\Program Files\Nagios\NCPA\plugins\"

      - name: Run E2E Tests
        run: .\test\e2e\test_ncpa_e2e.ps1